apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.9.0
  targetNamespace: ingress-nginx
  valuesContent: |
    controller:
      replicaCount: 2
      service:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn-of-cert>
        targetPorts:
          http: http
          https: http
      extraArgs:
        default-ssl-certificate: ingress-nginx/<secret-name>
